// ABOUTME: Tests the loading and merging of content/**.md against the real files.
// ABOUTME: Covers a written entry, a stub, the bilingual pair, the fallback, and annotated ids.

import { describe, expect, it } from 'vitest'
import {
  ROLES,
  contentProgress,
  getDungeonContent,
  getMobContent,
  inlineMarkdown,
  isRank,
  isRole,
  npcIdList,
} from './content'
import { dungeonList, getLookup, getNpcLabel, getSpell } from './data'

/**
 * These tests read the real files under `content/`. Two entries serve as landmarks: one is
 * written, the other is an untouched stub exactly as `npm run scaffold` produces it.
 *
 * The stub used to be *found* by scanning the pool for an unwritten entry. Every dungeon is
 * written now, so there is nothing left to find — and the codex being finished must not break
 * the tests that protect it. The stub therefore lives in `content/__fixtures__/`, generated by
 * the real `buildMobStub()` from the real committed `scripts/__fixtures__/AltarOfFangs.lua`.
 * It is not a hand-written imitation: `content-stub.test.mjs` regenerates it and fails if the
 * committed file has drifted from what the scaffold produces today.
 *
 * The fixture slug matches no dungeon in the pool, so it is invisible to the app.
 */
const SLUG = 'altar-of-fangs'
const WRITTEN = 270306 // Ritual Chieftain
const NO_ENTRY = 999_999

/** The untouched scaffold output — same mob as WRITTEN, before anybody wrote anything. */
const stub = { slug: '__fixtures__', npcId: 270306 }

/**
 * A written base carrying a deliberately partial translation, and an untranslated plan.
 *
 * Both used to be *found* by scanning the pool for content nobody had translated. That worked
 * only while the translation was incomplete, which is the one thing it is meant to stop being:
 * the subject vanishes the day the writing is finished, and a test must not go red for having
 * succeeded. They are fixtures for the same reason the stub above is one, and their own
 * comments say what each field is pinning.
 */
const partial = { slug: '__fixtures__', npcId: 263_109 }
const untranslatedPlan = '__fixtures__'

describe('isRole', () => {
  it('recognises the vocabulary the scaffold template offers', () => {
    for (const role of ROLES) expect(isRole(role), role).toBe(true)
  })

  it('rejects anything else, so an unexpected value can pass through untranslated', () => {
    // `role` is free text in the frontmatter: a typo or a word we never planned must not
    // become a missing translation key on screen.
    expect(isRole('healer')).toBe(false)
    expect(isRole('Melee')).toBe(false)
    expect(isRole('')).toBe(false)
    expect(isRole(undefined)).toBe(false)
  })
})

describe('Written mob entry', () => {
  const entry = getMobContent(SLUG, WRITTEN)

  it('exists and carries its npcId', () => {
    expect(entry).toBeDefined()
    expect(entry!.npcId).toBe(WRITTEN)
  })

  it('reads the human judgement out of the frontmatter', () => {
    expect(entry!.threat).toBe('high')
    expect(entry!.role).toBe('melee')
    // The trap is judgement and gets rewritten; assert that it is carried, not what it says.
    expect(entry!.trap).toBeTruthy()
  })

  it('keeps the spell annotations with their tag and priority', () => {
    const dismember = entry!.spells?.find((s) => s.id === 1306911)
    expect(dismember).toMatchObject({ tag: 'tank', prio: 1 })
    expect(dismember!.note).toContain('581k')
  })

  it('converts the prose to HTML', () => {
    expect(entry!.html).toContain('<p>')
    expect(entry!.html).toContain('<strong>Dismember</strong>')
  })

  it('does not emit the HTML helper comments into the render', () => {
    expect(entry!.html).not.toContain('<!--')
    expect(entry!.html).not.toContain('To confirm in game')
  })

  it('does not count as a stub', () => {
    expect(entry!.isStub).toBe(false)
  })
})

describe('Unwritten stub', () => {
  const entry = getMobContent(stub.slug, stub.npcId)

  it('loads even though nothing has been written', () => {
    expect(entry).toBeDefined()
    expect(entry!.npcId).toBe(stub.npcId)
  })

  it('invents no judgement: no threat, no trap, no prose', () => {
    expect(entry!.threat).toBeFalsy()
    expect(entry!.trap).toBeFalsy()
    expect(entry!.html.trim()).toBe('')
  })

  it('is marked as a stub: `tag: todo` does not count as writing', () => {
    expect(entry!.isStub).toBe(true)
    expect(entry!.spells?.every((s) => s.tag === 'todo')).toBe(true)
  })
})

describe('Mob with no file', () => {
  it('returns undefined rather than failing — the codex fills in gradually', () => {
    expect(getMobContent(SLUG, NO_ENTRY)).toBeUndefined()
  })

  it('returns undefined for an unknown dungeon', () => {
    expect(getMobContent('no-such-dungeon', WRITTEN)).toBeUndefined()
  })
})

describe('Dungeon entry', () => {
  it('loads `_dungeon.md` and renders its route plan', () => {
    const dungeon = getDungeonContent(SLUG)
    expect(dungeon).toBeDefined()
    expect(dungeon!.html).toContain('Route plan')
  })

  it('leaves timer and summary empty until they are filled in', () => {
    const dungeon = getDungeonContent(SLUG)!
    expect(dungeon.timer).toBeFalsy()
    expect(dungeon.summary).toBeFalsy()
  })

  it('returns undefined for an unknown dungeon', () => {
    expect(getDungeonContent('no-such-dungeon')).toBeUndefined()
  })
})

/**
 * Ritual Chieftain is the reference bilingual entry: an English base
 * (`270306-ritual-chieftain.md`) and a French translation (`.fr.md`) carrying text only.
 * That pair is what exercises the field-by-field merge.
 */
describe('Translated entry', () => {
  const base = getMobContent(SLUG, WRITTEN, 'en')!
  const translated = getMobContent(SLUG, WRITTEN, 'fr')!

  it('takes the text from the translation', () => {
    // What matters is that the French text overrides the English one, not its wording.
    expect(translated.trap).toBeTruthy()
    expect(translated.trap).not.toBe(base.trap)
    expect(translated.html).toContain('séquence qui tue')
  })

  it('inherits the judgements from the base, which the translation does not repeat', () => {
    // `threat`, `role`, `tag` and `prio` do not appear in the .fr.md: duplicating them would
    // guarantee they drift apart eventually.
    expect(translated.threat).toBe('high')
    expect(translated.role).toBe('melee')
    expect(translated.spells?.find((s) => s.id === 1306911)).toMatchObject({ tag: 'tank', prio: 1 })
  })

  it('merges the spell notes by id', () => {
    const dismemberFr = translated.spells?.find((s) => s.id === 1306911)
    const dismemberEn = base.spells?.find((s) => s.id === 1306911)
    expect(dismemberFr!.note).toContain('581k physique')
    expect(dismemberEn!.note).toContain('581k physical')
    expect(translated.spells).toHaveLength(base.spells!.length)
  })

  it('counts as written in both languages', () => {
    expect(base.isStub).toBe(false)
    expect(translated.isStub).toBe(false)
  })
})

describe('Falling back to the base language', () => {
  it('serves the base entry when the translation is missing', () => {
    // The stub has no .fr.md: a French reader sees the base rather than a hole.
    expect(getMobContent(stub.slug, stub.npcId, 'fr')).toEqual(
      getMobContent(stub.slug, stub.npcId, 'en'),
    )
  })

  it('serves the base dungeon plan in both languages', () => {
    expect(getDungeonContent(untranslatedPlan, 'fr')!.html).toBe(
      getDungeonContent(untranslatedPlan, 'en')!.html,
    )
  })

  it('fabricates nothing for a mob with no file at all', () => {
    expect(getMobContent(SLUG, NO_ENTRY, 'fr')).toBeUndefined()
  })
})

/**
 * Which text fields the reader is being served in the base language rather than their own.
 *
 * The merge falls back per field, so a card can be half translated without anything saying
 * so, and one of those fields is the spell note — which the card shows *instead of* Wowhead's
 * description, French and available. Silently serving English over available French is the
 * case this exists to make visible.
 *
 * A missing `.fr.md` and a `.fr.md` that omits the field are the same condition and take the
 * same expression, so one partially translated fixture covers both: there is no second branch
 * for a fixture to reach.
 */
describe('Fallback provenance', () => {
  it('names the fields still reading in the base language', () => {
    const { fallback } = getMobContent(partial.slug, partial.npcId, 'fr')!
    // The fixture translates the trap and the note on 1307567, and nothing else.
    expect(fallback).toEqual({ trap: false, prose: true, tips: true, notes: [1306852] })
  })

  it('marks nothing when the reader asked for the base language', () => {
    const { fallback } = getMobContent(partial.slug, partial.npcId, 'en')!
    expect(fallback).toEqual({ trap: false, prose: false, tips: false, notes: [] })
  })

  it('marks nothing on an entry translated all the way through', () => {
    const { fallback } = getMobContent(SLUG, WRITTEN, 'fr')!
    expect(fallback).toEqual({ trap: false, prose: false, tips: false, notes: [] })
  })

  it('marks nothing on a stub: an empty field has no base text to fall back to', () => {
    // The stub has no .fr.md at all, and still nothing is a fallback — there is nothing there.
    const { fallback } = getMobContent(stub.slug, stub.npcId, 'fr')!
    expect(fallback).toEqual({ trap: false, prose: false, tips: false, notes: [] })
  })
})

/**
 * Every annotated spell id must be one MDT attaches to that mob.
 *
 * `getIndicators` and `MobCard` both iterate `enemy.spells` and look each id up among the
 * notes, never the reverse. An annotation whose id is absent from that list therefore renders
 * nowhere at all — no row, no note, no tag, no priority. It is not a degraded display but
 * silent dead content, and nothing else in the suite would notice it.
 *
 * This sweep can only go red because of a commit in this repository: `src/data/generated/` is
 * versioned and CI runs no extraction, so the spell lists never move on their own. Either an
 * entry names an id the data does not carry, or a `npm run data` refresh moved a spell out
 * from under a written note. Both are for a human to resolve, and this is when to say so.
 *
 * It deliberately does not require the converse: a spell MDT lists and nobody annotated is
 * the normal state of an unwritten codex, and it still renders from the MDT data alone.
 */
describe('Annotated spell ids', () => {
  // Keyed by dungeon, mob and id, so a note a translation inherits from its base is reported
  // once rather than once per language.
  const orphans = new Map<string, string>()

  for (const summary of dungeonList) {
    const lookup = getLookup(summary.slug)
    if (!lookup) continue
    for (const enemy of lookup.dungeon.enemies) {
      const known = new Set(enemy.spells.map((s) => s.id))
      // Both locales: a translation can carry a note the base never had, and merging is by id.
      for (const locale of ['en', 'fr'] as const) {
        for (const note of getMobContent(summary.slug, enemy.id, locale)?.spells ?? []) {
          if (known.has(Number(note.id))) continue
          orphans.set(
            `${summary.slug}/${enemy.id}/${note.id}`,
            `content/${summary.slug}/${enemy.id}-* annotates ${note.id}` +
              ` (tag: ${note.tag ?? 'none'}), which MDT does not list for ${enemy.name}.` +
              ` It lists: ${[...known].join(', ')}`,
          )
        }
      }
    }
  }

  it('are all spells MDT attaches to that mob, so every note reaches the card', () => {
    expect([...orphans.values()]).toEqual([])
  })
})

/**
 * Every cross-link a card writes must address a card the router actually serves.
 *
 * `marked` emits the href verbatim and nothing in the app rewrites it, so a wrong address is
 * not a degraded link: `App.tsx` serves no `/d/:slug/mob/:npcId`, and its catch-all sends the
 * reader to the home page instead. That is the quietest kind of broken link — it still looks
 * and behaves like a link, it simply arrives somewhere else.
 *
 * The target is checked as well as the shape. A link naming a mob that no longer sits in that
 * dungeon opens a codex with nothing focused, which is wrong in the same silent way.
 */
describe('Cross-links between cards', () => {
  /** The one address a mob card has, from the route table in `App.tsx`. */
  const CARD = /^#\/d\/([a-z0-9-]+)\/codex\/mob\/(\d+)$/
  const isExternal = (href: string) => /^(https?:|mailto:)/.test(href)

  // Keyed by mob and href so a link a translation inherits from its base is reported once.
  const offenders = new Map<string, string>()

  for (const summary of dungeonList) {
    const lookup = getLookup(summary.slug)
    if (!lookup) continue
    for (const enemy of lookup.dungeon.enemies) {
      for (const locale of ['en', 'fr'] as const) {
        const content = getMobContent(summary.slug, enemy.id, locale)
        if (!content) continue
        // Everything a card renders as markdown: the prose body, the trap, and every note.
        const rendered = [
          content.html,
          inlineMarkdown(content.trap),
          ...(content.spells ?? []).map((s) => inlineMarkdown(s.note)),
        ].join('\n')

        for (const [, href] of rendered.matchAll(/href="([^"]+)"/g)) {
          if (isExternal(href)) continue
          const where = `content/${summary.slug}/${enemy.id}-*`
          const key = `${summary.slug}/${enemy.id}/${href}`
          const m = CARD.exec(href)
          if (!m) {
            offenders.set(
              key,
              `${where} links to "${href}", which no route serves.` +
                ' A mob card is at #/d/<slug>/codex/mob/<npcId>.',
            )
            continue
          }
          const [, targetSlug, npcId] = m
          const target = getLookup(targetSlug)
          if (!target) {
            offenders.set(key, `${where} links to "${href}": no dungeon named ${targetSlug}.`)
          } else if (!target.enemyById.has(Number(npcId))) {
            offenders.set(key, `${where} links to "${href}": ${targetSlug} has no mob ${npcId}.`)
          }
        }
      }
    }
  }

  it('all address a mob card the router serves', () => {
    expect([...offenders.values()]).toEqual([])
  })

  /**
   * A link naming one mob must not point at another.
   *
   * The sweep above cannot see this: the address is well formed and the target really is in
   * that dungeon, so everything checks out except which mob it is. The reader clicks a name and
   * lands on a different card — and because both cards exist and both look plausible, nothing
   * about the result says it went wrong.
   *
   * Only flagged when the link text is *exactly* another mob's name, in either language. A
   * link whose text is a description ("the adds", "its cubs") is deliberate phrasing and is
   * left alone.
   *
   * A name maps to a **set** of ids, because thirteen names in the pool belong to two mobs each
   * — a boss and its encounter copy, Merektha as 133384 and 134487. Keeping one id per name
   * reported six correct links as wrong on the first run. The cost is that this cannot catch a
   * link to the wrong one of two mobs sharing a name; what it does catch is a link naming a mob
   * that has nothing to do with the target.
   */
  it('name the mob they point at, not a different one', () => {
    const named = new Map<string, Set<number>>()
    for (const summary of dungeonList) {
      for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
        for (const locale of ['en', 'fr'] as const) {
          const name = getNpcLabel(enemy, locale).name
          const ids = named.get(name) ?? new Set<number>()
          ids.add(enemy.id)
          named.set(name, ids)
        }
      }
    }

    const mismatched = new Map<string, string>()
    for (const summary of dungeonList) {
      for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
        for (const locale of ['en', 'fr'] as const) {
          const content = getMobContent(summary.slug, enemy.id, locale)
          if (!content) continue
          const source = [content.html, content.trap ?? ''].join('\n')

          const ANCHOR = /<a href="#\/d\/[a-z0-9-]+\/codex\/mob\/(\d+)">([^<]+)<\/a>/g
          for (const [, target, label] of source.matchAll(ANCHOR)) {
            const text = label.trim()
            const claimed = named.get(text)
            if (!claimed || claimed.has(Number(target))) continue
            mismatched.set(
              `${summary.slug}/${enemy.id}/${text}`,
              `content/${summary.slug}/${enemy.id}-* links "${text}" to mob ${target},` +
                ` but that name belongs to ${[...claimed].join(' / ')}.`,
            )
          }
        }
      }
    }

    expect([...mismatched.values()]).toEqual([])
  })
})

/**
 * A spell a translation names must be named in the reader's language.
 *
 * The chip, the badge and the card's own spell row all take their label from `spells.json`, so
 * a sentence that spells the name out in English disagrees with the row printed right next to
 * it — which is the version the reader trusts. Wowhead already gives us the French, so this is
 * a gap rather than a convention.
 *
 * **Emphasised spans, not any occurrence of the name.** Naming a spell in emphasis is the
 * house style, which makes the span the unit worth checking — and it is the only unit that can
 * be checked without false alarms. A bare substring sweep flags the `Disruption` inside
 * `Essence Disruption`, a name Method's guide carries and `spells.json` does not: it stays
 * English because we have nothing to replace it with, and a guard that cannot tell the
 * difference would be a guard nobody keeps green.
 */
describe('Spell names in the French entries', () => {
  /** English label -> French one, over every spell the pool can attach to a mob. */
  const french = new Map<string, string>()
  for (const summary of dungeonList) {
    for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
      for (const { id } of enemy.spells) {
        const en = getSpell(id, 'en')?.name
        const fr = getSpell(id, 'fr')?.name
        if (en && fr && en !== fr) french.set(en, fr)
      }
    }
  }

  const offenders = new Map<string, string>()
  for (const summary of dungeonList) {
    for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
      const content = getMobContent(summary.slug, enemy.id, 'fr')
      if (!content) continue
      // Only text the translation actually wrote. A field still falling back to the base is
      // English on purpose, and naming its spells in English is the one thing it should do.
      const rendered = [
        content.fallback.prose ? '' : content.html,
        content.fallback.trap ? '' : inlineMarkdown(content.trap),
        ...(content.spells ?? [])
          .filter((s) => !content.fallback.notes.includes(Number(s.id)))
          .map((s) => inlineMarkdown(s.note)),
      ].join('\n')

      for (const [, , name] of rendered.matchAll(/<(strong|em)>([^<]+)<\/\1>/g)) {
        const fr = french.get(name.trim())
        if (!fr) continue
        offenders.set(
          `${summary.slug}/${enemy.id}/${name}`,
          `content/${summary.slug}/${enemy.id}-*.fr.md emphasises "${name}",` +
            ` which the card next to it labels "${fr}".`,
        )
      }
    }
  }

  it('use the label the card itself shows', () => {
    expect([...offenders.values()]).toEqual([])
  })

  /**
   * The same rule, for the half of it a reader cannot see.
   *
   * Wowhead's French labels carry real typography: a non-breaking space before `!` or `:`, a
   * typographic apostrophe in `d’os`. Retyping a name by hand produces the lookalike — a plain
   * space, a straight quote — and the result is indistinguishable on screen from the label it
   * no longer matches. Every occurrence found when this was written had been introduced by
   * hand, in files whose visible text was already correct, so nothing but a byte comparison
   * was ever going to catch it.
   *
   * Only labels carrying one of those two characters are checked, and only their degraded
   * form: an ordinary French sentence has no reason to reproduce a spell's name exactly.
   */
  it('spell the label byte for byte, invisible characters included', () => {
    const NBSP = ' '
    const APOSTROPHE = '’'
    const degrade = (s: string) => s.replaceAll(NBSP, ' ').replaceAll(APOSTROPHE, "'")

    const tricky = new Set<string>()
    for (const summary of dungeonList) {
      for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
        for (const { id } of enemy.spells) {
          const fr = getSpell(id, 'fr')?.name
          if (fr && degrade(fr) !== fr) tricky.add(fr)
        }
      }
    }

    const degraded = new Map<string, string>()
    for (const summary of dungeonList) {
      for (const enemy of getLookup(summary.slug)?.dungeon.enemies ?? []) {
        const content = getMobContent(summary.slug, enemy.id, 'fr')
        if (!content) continue
        const written = [
          content.fallback.prose ? '' : content.html,
          content.fallback.trap ? '' : (content.trap ?? ''),
          ...(content.spells ?? [])
            .filter((s) => !content.fallback.notes.includes(Number(s.id)))
            .map((s) => s.note ?? ''),
        ].join('\n')

        for (const label of tricky) {
          if (!written.includes(degrade(label))) continue
          degraded.set(
            `${summary.slug}/${enemy.id}/${label}`,
            `content/${summary.slug}/${enemy.id}-*.fr.md writes "${degrade(label)}"` +
              ` where the label is "${label}".`,
          )
        }
      }
    }

    expect([...degraded.values()]).toEqual([])
  })
})

describe('contentProgress', () => {
  it('only counts entries carrying actual writing', () => {
    expect(contentProgress(SLUG, [WRITTEN])).toEqual({ written: 1, total: 1 })
    expect(contentProgress(stub.slug, [stub.npcId])).toEqual({ written: 0, total: 1 })
  })

  it('counts what the reader sees: a fallback to the base counts as readable', () => {
    // Ritual Chieftain is written in both languages; the stub is written in neither. Neither
    // count changes with the locale, because the fallback serves the base either way.
    expect(contentProgress(SLUG, [WRITTEN], 'fr')).toEqual({ written: 1, total: 1 })
    expect(contentProgress(stub.slug, [stub.npcId], 'fr')).toEqual({ written: 0, total: 1 })
  })

  it('counts a mob with no file as unwritten', () => {
    expect(contentProgress(SLUG, [NO_ENTRY])).toEqual({ written: 0, total: 1 })
  })

  it('returns a zero total for an empty list', () => {
    expect(contentProgress(SLUG, [])).toEqual({ written: 0, total: 0 })
  })
})

/**
 * `note` and `trap` are single sentences rendered inside a paragraph, so they take *inline*
 * markdown: emphasis and links, but no block wrapper. The prose body keeps `render()`.
 */
describe('inlineMarkdown', () => {
  it('renders emphasis without wrapping it in a block', () => {
    expect(inlineMarkdown('**Dispel** the enrage')).toBe('<strong>Dispel</strong> the enrage')
  })

  it('leaves plain text alone', () => {
    expect(inlineMarkdown('581k on the current target.')).toBe('581k on the current target.')
  })

  it('is empty for nothing, so callers can render it unconditionally', () => {
    expect(inlineMarkdown(undefined)).toBe('')
    expect(inlineMarkdown('')).toBe('')
  })
})

describe('npcIdList', () => {
  it('reads a hand-written list of ids', () => {
    expect(npcIdList([135322, 134993])).toEqual([135322, 134993])
  })

  it('drops anything that is not a list of ids, rather than trusting it', () => {
    // `bosses:` is typed by hand in YAML. An empty field parses to null, a typo to a string;
    // neither must reach the ordering code as a half-valid array.
    expect(npcIdList(null)).toBeUndefined()
    expect(npcIdList(undefined)).toBeUndefined()
    expect(npcIdList('135322')).toBeUndefined()
    expect(npcIdList([])).toBeUndefined()
    expect(npcIdList(['nope', 0, -3])).toBeUndefined()
  })

  it('keeps the ids it recognises and discards the rest of the list', () => {
    expect(npcIdList([135322, 'nope'])).toEqual([135322])
  })
})

describe('Tips', () => {
  const withTips = getMobContent('__fixtures__', 263_109)

  it('reads the three kinds off the frontmatter', () => {
    expect(withTips!.tips).toEqual([
      { kind: 'text', text: 'Fixture tip: the sentence a reader gets when no translation exists yet.' },
      { kind: 'video', videoId: '9D0gCU8Tp5Y', portrait: true, label: 'Fixture video' },
      { kind: 'image', file: 'example.webp', label: 'Fixture image' },
    ])
  })

  it('falls back to the base list, and says so, when the translation carries none', () => {
    const fr = getMobContent('__fixtures__', 263_109, 'fr')
    expect(fr!.tips).toEqual(withTips!.tips)
    expect(fr!.fallback.tips).toBe(true)
  })

  it('replaces the whole list when the translation names the key', () => {
    const en = getMobContent('__fixtures__', 888_002)
    const fr = getMobContent('__fixtures__', 888_002, 'fr')
    expect(en!.tips).toEqual([{ kind: 'text', text: 'Base tip.' }])
    expect(fr!.tips).toEqual([{ kind: 'text', text: 'Astuce traduite.' }])
    expect(fr!.fallback.tips).toBe(false)
  })

  it('never marks a fallback in the base language itself', () => {
    expect(withTips!.fallback.tips).toBe(false)
  })

  it('counts a card carrying nothing but a tip as written', () => {
    // 888002 has no threat, no trap, no prose and no annotated spell — only a tip. Someone who
    // found the video that explains the fight has put something here, and the bar measures
    // whether there is anything to read.
    expect(getMobContent('__fixtures__', 888_002)!.isStub).toBe(false)
  })
})

describe('getDungeonContent bosses', () => {
  it('reads the order a dungeon declares', () => {
    // King's Rest is the one dungeon whose mdtIdx order is wrong: King Dazar, its last boss,
    // sits at index 25 while the Council of Tribes was re-added at 34-36.
    expect(getDungeonContent('kings-rest')?.bosses).toEqual([
      135322, 134993, 269808, 269810, 269811, 136160,
    ])
  })

  it('leaves it undefined where no order is declared, so mdtIdx stands', () => {
    expect(getDungeonContent('altar-of-fangs')?.bosses).toBeUndefined()
  })
})

describe('rank', () => {
  it('reads a legal value off a card', () => {
    expect(getMobContent('__fixtures__', 888_010)?.rank).toBe('miniboss')
  })

  it('leaves rank undefined on a card that declares none', () => {
    expect(getMobContent('__fixtures__', 270_306)?.rank).toBeUndefined()
  })

  // `role` is displayed, so a typo renders verbatim and the reader sees what was written.
  // `rank` decides placement and is never displayed as text, so the same tolerance would drop a
  // boss off the Overview with nothing on screen to say so. Ignoring it leaves MDT's answer
  // standing, which is the safe direction; `content.integrity.test.ts` is what catches the typo.
  it('rejects a value outside the vocabulary', () => {
    expect(isRank('boss')).toBe(true)
    expect(isRank('miniboss')).toBe(true)
    expect(isRank('bos')).toBe(false)
    expect(isRank('')).toBe(false)
    expect(isRank(undefined)).toBe(false)
    expect(isRank(3)).toBe(false)
  })
})

describe('miniboss leaves the shape vocabulary', () => {
  // It was never a shape: a mob is a caster or a melee *and* a miniboss. The rank field is
  // where it lives now, and leaving it in `ROLES` would keep offering the old spelling.
  it('no longer offers miniboss as a shape', () => {
    expect(isRole('miniboss')).toBe(false)
    expect(ROLES).not.toContain('miniboss')
  })
})
