// ABOUTME: Tests the loading and merging of content/**.md against the real files.
// ABOUTME: Covers a written entry, a stub, the bilingual pair, the fallback, and annotated ids.

import { describe, expect, it } from 'vitest'
import {
  ROLES,
  contentProgress,
  getDungeonContent,
  getMobContent,
  inlineMarkdown,
  isRole,
  npcIdList,
} from './content'
import { dungeonList, getLookup } from './data'

/**
 * These tests read the real files under `content/`. Two entries serve as landmarks: one is
 * written, the other is an untouched stub exactly as `npm run scaffold` produces it.
 *
 * The stub used to be *found* by scanning the pool for an unwritten entry. Every dungeon is
 * written now, so there is nothing left to find — and the codex being finished must not break
 * the tests that protect it. The stub therefore lives in `content/__fixtures__/`, generated by
 * the real `buildMobStub()` from the real committed `scripts/__fixtures__/AltarOfFangs.lua`.
 * It is not a hand-written imitation: `content-stub.test.mjs` regenerates it and fails if the
 * committed file has drifted from what the scaffold produces today.
 *
 * The fixture slug matches no dungeon in the pool, so it is invisible to the app.
 */
const SLUG = 'altar-of-fangs'
const WRITTEN = 270306 // Ritual Chieftain
const NO_ENTRY = 999_999

/** The untouched scaffold output — same mob as WRITTEN, before anybody wrote anything. */
const stub = { slug: '__fixtures__', npcId: 270306 }

/**
 * A written base carrying a deliberately partial translation, and an untranslated plan.
 *
 * Both used to be *found* by scanning the pool for content nobody had translated. That worked
 * only while the translation was incomplete, which is the one thing it is meant to stop being:
 * the subject vanishes the day the writing is finished, and a test must not go red for having
 * succeeded. They are fixtures for the same reason the stub above is one, and their own
 * comments say what each field is pinning.
 */
const partial = { slug: '__fixtures__', npcId: 263_109 }
const untranslatedPlan = '__fixtures__'

describe('isRole', () => {
  it('recognises the vocabulary the scaffold template offers', () => {
    for (const role of ROLES) expect(isRole(role), role).toBe(true)
  })

  it('rejects anything else, so an unexpected value can pass through untranslated', () => {
    // `role` is free text in the frontmatter: a typo or a word we never planned must not
    // become a missing translation key on screen.
    expect(isRole('healer')).toBe(false)
    expect(isRole('Melee')).toBe(false)
    expect(isRole('')).toBe(false)
    expect(isRole(undefined)).toBe(false)
  })
})

describe('Written mob entry', () => {
  const entry = getMobContent(SLUG, WRITTEN)

  it('exists and carries its npcId', () => {
    expect(entry).toBeDefined()
    expect(entry!.npcId).toBe(WRITTEN)
  })

  it('reads the human judgement out of the frontmatter', () => {
    expect(entry!.threat).toBe('high')
    expect(entry!.role).toBe('melee')
    // The trap is judgement and gets rewritten; assert that it is carried, not what it says.
    expect(entry!.trap).toBeTruthy()
  })

  it('keeps the spell annotations with their tag and priority', () => {
    const dismember = entry!.spells?.find((s) => s.id === 1306911)
    expect(dismember).toMatchObject({ tag: 'tank', prio: 1 })
    expect(dismember!.note).toContain('581k')
  })

  it('converts the prose to HTML', () => {
    expect(entry!.html).toContain('<p>')
    expect(entry!.html).toContain('<strong>Dismember</strong>')
  })

  it('does not emit the HTML helper comments into the render', () => {
    expect(entry!.html).not.toContain('<!--')
    expect(entry!.html).not.toContain('To confirm in game')
  })

  it('does not count as a stub', () => {
    expect(entry!.isStub).toBe(false)
  })
})

describe('Unwritten stub', () => {
  const entry = getMobContent(stub.slug, stub.npcId)

  it('loads even though nothing has been written', () => {
    expect(entry).toBeDefined()
    expect(entry!.npcId).toBe(stub.npcId)
  })

  it('invents no judgement: no threat, no trap, no prose', () => {
    expect(entry!.threat).toBeFalsy()
    expect(entry!.trap).toBeFalsy()
    expect(entry!.html.trim()).toBe('')
  })

  it('is marked as a stub: `tag: todo` does not count as writing', () => {
    expect(entry!.isStub).toBe(true)
    expect(entry!.spells?.every((s) => s.tag === 'todo')).toBe(true)
  })
})

describe('Mob with no file', () => {
  it('returns undefined rather than failing — the codex fills in gradually', () => {
    expect(getMobContent(SLUG, NO_ENTRY)).toBeUndefined()
  })

  it('returns undefined for an unknown dungeon', () => {
    expect(getMobContent('no-such-dungeon', WRITTEN)).toBeUndefined()
  })
})

describe('Dungeon entry', () => {
  it('loads `_dungeon.md` and renders its route plan', () => {
    const dungeon = getDungeonContent(SLUG)
    expect(dungeon).toBeDefined()
    expect(dungeon!.html).toContain('Route plan')
  })

  it('leaves timer and summary empty until they are filled in', () => {
    const dungeon = getDungeonContent(SLUG)!
    expect(dungeon.timer).toBeFalsy()
    expect(dungeon.summary).toBeFalsy()
  })

  it('returns undefined for an unknown dungeon', () => {
    expect(getDungeonContent('no-such-dungeon')).toBeUndefined()
  })
})

/**
 * Ritual Chieftain is the reference bilingual entry: an English base
 * (`270306-ritual-chieftain.md`) and a French translation (`.fr.md`) carrying text only.
 * That pair is what exercises the field-by-field merge.
 */
describe('Translated entry', () => {
  const base = getMobContent(SLUG, WRITTEN, 'en')!
  const translated = getMobContent(SLUG, WRITTEN, 'fr')!

  it('takes the text from the translation', () => {
    // What matters is that the French text overrides the English one, not its wording.
    expect(translated.trap).toBeTruthy()
    expect(translated.trap).not.toBe(base.trap)
    expect(translated.html).toContain('séquence qui tue')
  })

  it('inherits the judgements from the base, which the translation does not repeat', () => {
    // `threat`, `role`, `tag` and `prio` do not appear in the .fr.md: duplicating them would
    // guarantee they drift apart eventually.
    expect(translated.threat).toBe('high')
    expect(translated.role).toBe('melee')
    expect(translated.spells?.find((s) => s.id === 1306911)).toMatchObject({ tag: 'tank', prio: 1 })
  })

  it('merges the spell notes by id', () => {
    const dismemberFr = translated.spells?.find((s) => s.id === 1306911)
    const dismemberEn = base.spells?.find((s) => s.id === 1306911)
    expect(dismemberFr!.note).toContain('581k physique')
    expect(dismemberEn!.note).toContain('581k physical')
    expect(translated.spells).toHaveLength(base.spells!.length)
  })

  it('counts as written in both languages', () => {
    expect(base.isStub).toBe(false)
    expect(translated.isStub).toBe(false)
  })
})

describe('Falling back to the base language', () => {
  it('serves the base entry when the translation is missing', () => {
    // The stub has no .fr.md: a French reader sees the base rather than a hole.
    expect(getMobContent(stub.slug, stub.npcId, 'fr')).toEqual(
      getMobContent(stub.slug, stub.npcId, 'en'),
    )
  })

  it('serves the base dungeon plan in both languages', () => {
    expect(getDungeonContent(untranslatedPlan, 'fr')!.html).toBe(
      getDungeonContent(untranslatedPlan, 'en')!.html,
    )
  })

  it('fabricates nothing for a mob with no file at all', () => {
    expect(getMobContent(SLUG, NO_ENTRY, 'fr')).toBeUndefined()
  })
})

/**
 * Which text fields the reader is being served in the base language rather than their own.
 *
 * The merge falls back per field, so a card can be half translated without anything saying
 * so, and one of those fields is the spell note — which the card shows *instead of* Wowhead's
 * description, French and available. Silently serving English over available French is the
 * case this exists to make visible.
 *
 * A missing `.fr.md` and a `.fr.md` that omits the field are the same condition and take the
 * same expression, so one partially translated fixture covers both: there is no second branch
 * for a fixture to reach.
 */
describe('Fallback provenance', () => {
  it('names the fields still reading in the base language', () => {
    const { fallback } = getMobContent(partial.slug, partial.npcId, 'fr')!
    // The fixture translates the trap and the note on 1307567, and nothing else.
    expect(fallback).toEqual({ trap: false, prose: true, notes: [1306852] })
  })

  it('marks nothing when the reader asked for the base language', () => {
    const { fallback } = getMobContent(partial.slug, partial.npcId, 'en')!
    expect(fallback).toEqual({ trap: false, prose: false, notes: [] })
  })

  it('marks nothing on an entry translated all the way through', () => {
    const { fallback } = getMobContent(SLUG, WRITTEN, 'fr')!
    expect(fallback).toEqual({ trap: false, prose: false, notes: [] })
  })

  it('marks nothing on a stub: an empty field has no base text to fall back to', () => {
    // The stub has no .fr.md at all, and still nothing is a fallback — there is nothing there.
    const { fallback } = getMobContent(stub.slug, stub.npcId, 'fr')!
    expect(fallback).toEqual({ trap: false, prose: false, notes: [] })
  })
})

/**
 * Every annotated spell id must be one MDT attaches to that mob.
 *
 * `getIndicators` and `MobCard` both iterate `enemy.spells` and look each id up among the
 * notes, never the reverse. An annotation whose id is absent from that list therefore renders
 * nowhere at all — no row, no note, no tag, no priority. It is not a degraded display but
 * silent dead content, and nothing else in the suite would notice it.
 *
 * This sweep can only go red because of a commit in this repository: `src/data/generated/` is
 * versioned and CI runs no extraction, so the spell lists never move on their own. Either an
 * entry names an id the data does not carry, or a `npm run data` refresh moved a spell out
 * from under a written note. Both are for a human to resolve, and this is when to say so.
 *
 * It deliberately does not require the converse: a spell MDT lists and nobody annotated is
 * the normal state of an unwritten codex, and it still renders from the MDT data alone.
 */
describe('Annotated spell ids', () => {
  // Keyed by dungeon, mob and id, so a note a translation inherits from its base is reported
  // once rather than once per language.
  const orphans = new Map<string, string>()

  for (const summary of dungeonList) {
    const lookup = getLookup(summary.slug)
    if (!lookup) continue
    for (const enemy of lookup.dungeon.enemies) {
      const known = new Set(enemy.spells.map((s) => s.id))
      // Both locales: a translation can carry a note the base never had, and merging is by id.
      for (const locale of ['en', 'fr'] as const) {
        for (const note of getMobContent(summary.slug, enemy.id, locale)?.spells ?? []) {
          if (known.has(Number(note.id))) continue
          orphans.set(
            `${summary.slug}/${enemy.id}/${note.id}`,
            `content/${summary.slug}/${enemy.id}-* annotates ${note.id}` +
              ` (tag: ${note.tag ?? 'none'}), which MDT does not list for ${enemy.name}.` +
              ` It lists: ${[...known].join(', ')}`,
          )
        }
      }
    }
  }

  it('are all spells MDT attaches to that mob, so every note reaches the card', () => {
    expect([...orphans.values()]).toEqual([])
  })
})

/**
 * Every cross-link a card writes must address a card the router actually serves.
 *
 * `marked` emits the href verbatim and nothing in the app rewrites it, so a wrong address is
 * not a degraded link: `App.tsx` serves no `/d/:slug/mob/:npcId`, and its catch-all sends the
 * reader to the home page instead. That is the quietest kind of broken link — it still looks
 * and behaves like a link, it simply arrives somewhere else.
 *
 * The target is checked as well as the shape. A link naming a mob that no longer sits in that
 * dungeon opens a codex with nothing focused, which is wrong in the same silent way.
 */
describe('Cross-links between cards', () => {
  /** The one address a mob card has, from the route table in `App.tsx`. */
  const CARD = /^#\/d\/([a-z0-9-]+)\/codex\/mob\/(\d+)$/
  const isExternal = (href: string) => /^(https?:|mailto:)/.test(href)

  // Keyed by mob and href so a link a translation inherits from its base is reported once.
  const offenders = new Map<string, string>()

  for (const summary of dungeonList) {
    const lookup = getLookup(summary.slug)
    if (!lookup) continue
    for (const enemy of lookup.dungeon.enemies) {
      for (const locale of ['en', 'fr'] as const) {
        const content = getMobContent(summary.slug, enemy.id, locale)
        if (!content) continue
        // Everything a card renders as markdown: the prose body, the trap, and every note.
        const rendered = [
          content.html,
          inlineMarkdown(content.trap),
          ...(content.spells ?? []).map((s) => inlineMarkdown(s.note)),
        ].join('\n')

        for (const [, href] of rendered.matchAll(/href="([^"]+)"/g)) {
          if (isExternal(href)) continue
          const where = `content/${summary.slug}/${enemy.id}-*`
          const key = `${summary.slug}/${enemy.id}/${href}`
          const m = CARD.exec(href)
          if (!m) {
            offenders.set(
              key,
              `${where} links to "${href}", which no route serves.` +
                ' A mob card is at #/d/<slug>/codex/mob/<npcId>.',
            )
            continue
          }
          const [, targetSlug, npcId] = m
          const target = getLookup(targetSlug)
          if (!target) {
            offenders.set(key, `${where} links to "${href}": no dungeon named ${targetSlug}.`)
          } else if (!target.enemyById.has(Number(npcId))) {
            offenders.set(key, `${where} links to "${href}": ${targetSlug} has no mob ${npcId}.`)
          }
        }
      }
    }
  }

  it('all address a mob card the router serves', () => {
    expect([...offenders.values()]).toEqual([])
  })
})

describe('contentProgress', () => {
  it('only counts entries carrying actual writing', () => {
    expect(contentProgress(SLUG, [WRITTEN])).toEqual({ written: 1, total: 1 })
    expect(contentProgress(stub.slug, [stub.npcId])).toEqual({ written: 0, total: 1 })
  })

  it('counts what the reader sees: a fallback to the base counts as readable', () => {
    // Ritual Chieftain is written in both languages; the stub is written in neither. Neither
    // count changes with the locale, because the fallback serves the base either way.
    expect(contentProgress(SLUG, [WRITTEN], 'fr')).toEqual({ written: 1, total: 1 })
    expect(contentProgress(stub.slug, [stub.npcId], 'fr')).toEqual({ written: 0, total: 1 })
  })

  it('counts a mob with no file as unwritten', () => {
    expect(contentProgress(SLUG, [NO_ENTRY])).toEqual({ written: 0, total: 1 })
  })

  it('returns a zero total for an empty list', () => {
    expect(contentProgress(SLUG, [])).toEqual({ written: 0, total: 0 })
  })
})

/**
 * `note` and `trap` are single sentences rendered inside a paragraph, so they take *inline*
 * markdown: emphasis and links, but no block wrapper. The prose body keeps `render()`.
 */
describe('inlineMarkdown', () => {
  it('renders emphasis without wrapping it in a block', () => {
    expect(inlineMarkdown('**Dispel** the enrage')).toBe('<strong>Dispel</strong> the enrage')
  })

  it('leaves plain text alone', () => {
    expect(inlineMarkdown('581k on the current target.')).toBe('581k on the current target.')
  })

  it('is empty for nothing, so callers can render it unconditionally', () => {
    expect(inlineMarkdown(undefined)).toBe('')
    expect(inlineMarkdown('')).toBe('')
  })
})

describe('npcIdList', () => {
  it('reads a hand-written list of ids', () => {
    expect(npcIdList([135322, 134993])).toEqual([135322, 134993])
  })

  it('drops anything that is not a list of ids, rather than trusting it', () => {
    // `bosses:` is typed by hand in YAML. An empty field parses to null, a typo to a string;
    // neither must reach the ordering code as a half-valid array.
    expect(npcIdList(null)).toBeUndefined()
    expect(npcIdList(undefined)).toBeUndefined()
    expect(npcIdList('135322')).toBeUndefined()
    expect(npcIdList([])).toBeUndefined()
    expect(npcIdList(['nope', 0, -3])).toBeUndefined()
  })

  it('keeps the ids it recognises and discards the rest of the list', () => {
    expect(npcIdList([135322, 'nope'])).toEqual([135322])
  })
})

describe('getDungeonContent bosses', () => {
  it('reads the order a dungeon declares', () => {
    // King's Rest is the one dungeon whose mdtIdx order is wrong: King Dazar, its last boss,
    // sits at index 25 while the Council of Tribes was re-added at 34-36.
    expect(getDungeonContent('kings-rest')?.bosses).toEqual([
      135322, 134993, 269808, 269810, 269811, 136160,
    ])
  })

  it('leaves it undefined where no order is declared, so mdtIdx stands', () => {
    expect(getDungeonContent('altar-of-fangs')?.bosses).toBeUndefined()
  })
})
